<h3>Reading</h3>
<p>One of my favourite past-times is reading novels.  From Harry Potter to Jason Bourne and beyond, I have read many novels over the years and am reading more and more as I spend more time working and less time in school.  Over time I have read many books, some of the series I have outlined here below</p>
<ul>
  <li><strong>Young Adult/Fantasy</strong></li>
  <li>MacDonald Hall - Gordan Korman wrote this series about two young men at a boarding school and documents the various pranks they pull off and other adventures that take place.  This is one of my the first series I read and led to me pursuing other novels by Gordon Korman</li>
  <li>Everest - A trilogy also written by Gordon Korman documenting the adventure of a group of teenagers who attempt to climb Mount Everest with the intention of becoming the youngest to ever reach the summit.</li>
  <li>The Magic Tree House - A series I unfortunately never completed as when I stopped reading there was 28 books and there are now well over 40 in the series.  This follows some young children as they are whisked through space and time in a Magic Tree House to take part in crazy adventures.</li>
  <li>Artemis Fowl - As I started to get a bit older, the books got a little longer.  This series is about a super genius kid who discoveries fairies and ends up forcing himself into their world and having to use his intellect and some cunning of some of the fairies to save their world from disaster.</li>
  <li>Inheritance Cycle - This was a fantastic series I read while in high school about a child in a fictional land discovering a dragon egg and then following his travels through training himself and his dragon and eventually fighting the all powerful King and freeing the people of his land.  A stereotypical story now that I write that, but a good one nonetheless</p>
  <li>Harry Potter - I won't even bother describing this.  If you haven't heard of Harry Potter, go and follow <a href="http://lmgtfy.com/?q=Harry+Potter">this link</a>.  I love this series but wish I could rip out the epilogue of the last book.  That is all.</li>
  <li><strong>Thriller/Action</strong></li>
  <li>Bourne - This is a series started by Robert Ludlum and continued by Eric Van Lustbader that chronicles the life of former CIA asset Jason Bourne after he has amnesia and multiple personality disorder.  Simply fantastic.  The movies based on the books are well known, but even though they are good, they don't do the novels justice and if you need your next book to read, follow this series</li>
  <li>Covert One - Another series started by Robert Ludlum and carried on by a number of authors, this follows Jon Smith, an army biologist who ends up becoming a member of a covert organization within the government sent in to resolve situations when government bureaucracy is too slow.  Similar feel to the Bourne series and another I highly recommend</li>
  <li>Everything else by Robert Ludlum - Ludlum authored many other novels, most of which I have read and recommend in addition to many others written as sequels to novels he wrote and also well written.  You can't go wrong here</li>
  <li>Other than these, I have also really enjoyed Dan Brown's novels as well as those of John Grisham and J.R.R Tolkien.  If you have books you recommend, please let me know and I will add them to my list.</li>
</ul>