<div class="interest-sm">
  <h3>Fiddler on the Roof</h3>
  <h4>Conrad Grebel University College Student Council (2014-2015)</h4>
  <a href="http://www.waterloochronicle.ca/whats-on/lchaim-to-life/">See Preview</a>
  <p>TRADITION! Tradition!  Fiddler on the roof is a musical based in Russia in the early 1900's.  The main characters involved are a family of Jews in the small town of Anatevka and addresses the issues of balancing tradition, happiness and religious values.  Tevye and Golde are the parents of a family of 5 girls.  Over the course of the musical the eldest 3 daughters all fall in love and in various different ways.</p>
  <p>The eldest, Tzietel is in love with the tailor's son Motel who is poor and timid.  Tzietel is pledged to the butcher Lazar Wolf but when Motel finally comes forward with the courage to ask for Tzietel's hand.  The next daughter, Hodel, falls in love with a radical named Perchik who leaves for Kiev just after pledging himself to Hodel and get arrested.  Perchik ends up in prison in Siberia and Hodel decides to join him there.  The third daughter, Chava, marries outside of the Jewish faith to a Russian by the name of Fyedka.</p>
  <p>This production follows these stories and the disruptions to their town as a result of this and the disturbance forced upon them during the Russian Revolution.  During our production, I was responsible for leading the stage hands, organizing the set design team and coordinating with the rest of the leadership team.  This involved finding all the necessary props, getting designers to build the larger set pieces and paint them.</p>
  <p>In summary, this was the third show I stage managed and the one I felt most comfortable doing.  The entire team we worked with was fantastic, and even while casting multiple understudies for lead roles in the final week of the show, the team never lost confidence that we would pull it off and we did.</p>
  <h3>Anne of Green Gables</h3>
  <h4>Conrad Grebel University College Student Council (2012-2013)</h4>
  <a href="http://grebelspeaks.weebly.com/imprint.html">See review</a>
  <p>My first student only production.  Amazing to see what happens to (mostly) first and second year university students with a passion for dramatic arts.  We were a bunch of people doing things for the first time with the exception of some of our actors and life saving technical director, but who could have predicted the outcome?  The props and costumes were contained at the house of one of our directors, the residence room of our other director and my room as stage manager.  During the final 2 weeks I was cutting props from the show as fast as we could find the props that I just couldn't quite find a reason to remove.  Turns out I'm not particularly cut out for tracking down props... or wasn't aware of the work it required at the time but I was good at reducing prop requirements.</p>
  <p>And the props weren't even the best part.  Due to the extensive choreography required of the show, the lack of prior dancing experience in the cast and restrictions on number of rehearsals, because, well we still were all students with homework and papers to do, we didn't actually have a chance to get a full run of the entire performance before we moved into the venue.  A venue we got 1 day before our first show, during which we had to hang the lights, run our cue to cue, have a dress rehearsal, bring in the props and costumes and keep our heads so the cast doesn't see the directorial team freaking out... not sure if we passed that test.  The cue to cue ran late resulting in dress rehearsal running late and all of a sudden we had to cut it so actors can get sleep and be ready for the first performance.  After a 1 am meeting back at the residence, many of us went to bed while others re wrote the mic schedule for the show and did various other preparatory tasks.  Next day is show day!</p>
  <p>A little to everyone's surprise, the first show went off without much of a hitch.  A few little things here and there but everything was beyond expectations.  The second show involved our set crashing down about 15 minutes from the end of the show, forcing one of our stage hands to hold it for the remainder of the show.  And then finally, the second and final day of performances came and went with 2 excellent shows making the entire team extremely proud of what they had accomplished.  The ragtag group of students pulled it off.  And we even managed to turn a profit.</p>
  <h3>Colours in the Storm</h3>
  <h4>E.L. Crossley Secondary School Drama Department (2011-2012)</h4>
  <a href="http://www.stcatharinesstandard.ca/2012/05/01/iconic-painters-artistic-perfection-recreated">See review</a>
  <p>This was my first production I was involved in.  My grade 12 year I was asked to stage manage by by drama teacher.  One of the best decisions I have ever made.  The first few months of production were focused on the biggest number of the show 'Girl with Thunder in her Hair', a number that resulted in some Irish dancing and endless hours of choreography and practice.  The rest of the time was spent scrambling to finish blocking the rest of the show and I have to say it turned out very well.  We had a week at the venue starting on Sunday.  The venue was relatively quiet the first few days with just our stage management team, our teacher who was directing and a few reliable cast members who doubled as do-it-all help.  After redoing the lights and choreography for one specific dance 3 times in 2 days, dress rehearsal came and went relatively smoothly.  I was in the booth calling cues and the rest of the team were backstage or at the sound/lighting boards.  All in all, we had a fantastic team that led to the performances going off without a hitch. Even an afternoon programming competition on the Saturday a 2 hour drive away didn't prevent me from being there to call all 4 shows.  I missed the cast picture and probably gave the director a minor heart attack, but we succeeded in pulling it off!  After the production, the stage crew was nominated for and won the Niagara Cappies award for best stage crew in a high school production in the region.</p>
  <p><a href="http://northernriver.com/coloursinthestorm.html">Colours in the Storm</a> is a Canadian written musical set in Algonquin park, exploring the life of Tom Thompson, a member of the <a href="http://en.wikipedia.org/wiki/Group_of_Seven_(artists)">Group of 7</a>.  It explores the mystery surrounding his death in the park and some of his relationships with various park characters in the years prior.  A fantastic show, expanded in our production to include a significantly expanded pit band, a chorus of dancers and no double cast roles, a first for any production of the show.  In the end, this production is what has helped keep my passion for drama alive, resulting in my participation in the 2 shows above.</p>
</div>